import { ThemeProvider } from '@/components/ThemeProvider';
import { cn } from '@/lib/utils';
import { Inter as FontSans } from 'next/font/google';
import '../globals.css';
import Nav from './site/_component/nav';

export const fontSans = FontSans({
	subsets: ['latin'],
	variable: '--font-sans',
});

export const metadata = {
	title: 'Wink | Connect together',
	description: 'Generated by Next.js',
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang='en' suppressHydrationWarning>
			<body
				className={cn(
					'min-h-screen font-sans bg-background text-foreground antialiased',
					fontSans.variable
				)}
			>
				<ThemeProvider attribute='class' defaultTheme='dark'>
					<Nav />
					<main>{children}</main>
				</ThemeProvider>
			</body>
		</html>
	);
}
