import Nav from '@/components/Layout/Nav';
import { ThemeProvider } from '@/components/ThemeProvider';
import { Toaster } from '@/components/ui/sonner';
import { cn } from '@/lib/utils';
import { Analytics } from '@vercel/analytics/react';
import type { Metadata } from 'next';
import { Inter as FontSans } from 'next/font/google';
import '../globals.css';

export const fontSans = FontSans({
	subsets: ['latin'],
	variable: '--font-sans',
});

export const metadata: Metadata = {
	title: {
		default: 'Chirp',
		template: `%s | Chirp`,
	},
	description: 'Generated by create next app',
	robots: {
		follow: true,
		index: true,
	},
	verification: {
		google: 'fmDb5LvLMBphFnbLxy0twqLiHhx4sOWt_ie3fZKiGwk',
	},
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang='en' suppressHydrationWarning>
			<body
				className={cn('min-h-screen font-sans antialiased', fontSans.variable)}
			>
				<ThemeProvider attribute='class' defaultTheme='dark'>
					<Toaster position='top-center' closeButton />
					<Nav />
					<main>{children}</main>
				</ThemeProvider>
				<Analytics />
			</body>
		</html>
	);
}
